-- Seed existing episodes into D1
-- Season 1
INSERT OR IGNORE INTO episodes (slug, title, description, speaker, season, season_episode, episode_number, date, duration, summary, topics, quote, spotify_id, status, created_at, updated_at)
VALUES
  ('s1-e1-arrastras-o-te-arrastran', 'Arrastras o te Arrastran', 'Episodio piloto donde presentamos al grupo mastermind de emprendedores. La conversación que lo empezó todo.', 'Punto Raw', 1, 1, 1, '2022-11-05', '39min', 'Episodio piloto donde presentamos al grupo mastermind de emprendedores. La conversación que lo empezó todo.', '["Origen del grupo mastermind","Presentación de los miembros","La filosofía detrás de Punto Raw","Tomar las riendas de tu vida","La importancia de rodearte de las personas correctas"]', 'O arrastras o te arrastran — tú decides.', '23xpSSaXeVq2db3m3CI0C', 'published', datetime('now'), datetime('now')),

  ('s1-e2-si-no-avanzas-retrocedes', 'Si No Avanzas, Retrocedes', 'Exploramos el progreso a través de acción intencional — metas reales, productividad vs. estar ocupado, y confrontación personal.', 'Punto Raw', 1, 2, 2, '2024-12-20', '1h 4min', 'Exploramos el progreso a través de acción intencional — metas reales, productividad vs. estar ocupado, y confrontación personal.', '["El estancamiento como retroceso","Metas reales vs. metas de ego","Productividad vs. estar ocupado","Confrontación personal y honestidad","Acción intencional como motor del progreso"]', 'No existe quedarse quieto — o avanzas, o retrocedes.', '1ShhNM0WE89japKcGqBBis', 'published', datetime('now'), datetime('now')),

  ('s1-e3-nunca-te-sientes-listo', 'Nunca te sientes listo... hasta que lo estás', 'Abordamos cómo el miedo a no estar preparados nos paraliza. El verdadero aprendizaje ocurre a través de la acción, no esperando a sentirte listo.', 'Punto Raw', 1, 3, 3, '2025-03-04', '1h 3min', 'Abordamos cómo el miedo a no estar preparados nos paraliza. El verdadero aprendizaje ocurre a través de la acción, no esperando a sentirte listo.', '["El mito de estar listo","Parálisis por análisis","Aprender haciendo vs. aprender planeando","Ejemplos reales de lanzarse sin estar preparado","Cómo el miedo disfraza la procrastinación"]', 'El verdadero aprendizaje ocurre a través de la acción, no esperando a sentirte listo.', '5ilMRgwvC72LxMBjhY5qC7', 'published', datetime('now'), datetime('now')),

  ('s1-e4-cambio-de-mentalidad', 'Cambio de mentalidad al éxito', 'Exploramos cuatro conceptos para transformar patrones de pensamiento: Genio Positivo, Arquitectura de Realidad, Metas Accesibles y Enfrentar la Oportunidad.', 'Punto Raw', 1, 4, 4, '2025-03-31', '1h 21min', 'Exploramos cuatro conceptos para transformar patrones de pensamiento: Genio Positivo, Arquitectura de Realidad, Metas Accesibles y Enfrentar la Oportunidad.', '["Genio Positivo — canalizar tu energía mental","Arquitectura de Realidad — diseñar tu entorno","Metas Accesibles — lo alcanzable como trampolín","Enfrentar la Oportunidad — actuar cuando se presenta"]', 'Transforma tus patrones de pensamiento y transformarás tu realidad.', '6xYI0jDvLegUljKvzky5vi', 'published', datetime('now'), datetime('now'));

-- Season 2
INSERT OR IGNORE INTO episodes (slug, title, description, speaker, season, season_episode, episode_number, date, duration, summary, topics, quote, spotify_id, status, created_at, updated_at)
VALUES
  ('s2-e1-the-walking-dead', 'The Walking Dead', '¿Te sientes como zombie en la vida? Exploramos qué significa realmente vivir, la diferencia entre metas y checkpoints, y por qué la disciplina supera a la motivación.', 'Punto Raw', 2, 1, 5, '2026-05-22', '1h 15min', '¿Te sientes como zombie en la vida? Exploramos qué significa realmente vivir, la diferencia entre metas y checkpoints, y por qué la disciplina supera a la motivación.', '["La diferencia entre existir y vivir","Metas vs. checkpoints — y por qué importa","Disciplina sobre motivación","Señales de que estás en piloto automático","Cómo despertar y tomar control"]', 'La disciplina supera a la motivación porque la motivación es temporal, la disciplina es una decisión.', '5QIPCJaU40wkoRpJ9BVDzE', 'published', datetime('now'), datetime('now')),

  ('s2-e2-piensas-o-confias', '¿Piensas o confías?', 'Hablamos sobre inteligencia artificial y si la gente realmente piensa críticamente sobre lo que la IA sugiere o simplemente confía sin cuestionar.', 'Punto Raw', 2, 2, 6, '2026-06-20', '1h 3min', 'Hablamos sobre inteligencia artificial y si la gente realmente piensa críticamente sobre lo que la IA sugiere o simplemente confía sin cuestionar.', '["Inteligencia artificial en la vida diaria","Pensamiento crítico vs. confianza ciega","El peligro de delegar decisiones a la tecnología","Cómo mantener tu criterio propio","El futuro de la relación humano-IA"]', '¿Realmente piensas críticamente sobre lo que la IA te sugiere o simplemente confías sin cuestionar?', '3VreLNayXOMjeSsnO7pDZt', 'published', datetime('now'), datetime('now')),

  ('s2-e3-conveniencia-destruccion', 'Conveniencia = Destrucción', 'Examinamos cómo la conveniencia tiene costos ocultos en tu vida — desde plásticos desechables hasta ingredientes procesados. Te retamos a abrazar alternativas incómodas.', 'Punto Raw', 2, 3, 7, '2026-07-03', '1h 5min', 'Examinamos cómo la conveniencia tiene costos ocultos en tu vida — desde plásticos desechables hasta ingredientes procesados. Te retamos a abrazar alternativas incómodas.', '["Costos ocultos de la conveniencia moderna","Plásticos desechables y su impacto real","Ingredientes procesados vs. alternativas naturales","El reto de elegir lo incómodo a propósito","Consumismo consciente"]', 'La conveniencia tiene costos ocultos que estamos pagando sin darnos cuenta.', '5t3RZujk56q0OmDNDqNW7L', 'published', datetime('now'), datetime('now')),

  ('s2-e4-algo-tiene-que-morir', 'Algo tiene que morir', 'Exploramos la entropía en la vida real — cómo nada se sostiene sin energía y por qué a veces lo más sano es dejar morir ciertas cosas para que nazcan otras nuevas.', 'Punto Raw', 2, 4, 8, '2026-08-08', '1h 3min', 'Exploramos la entropía en la vida real — cómo nada se sostiene sin energía y por qué a veces lo más sano es dejar morir ciertas cosas para que nazcan otras nuevas.', '["Entropía aplicada a la vida cotidiana","El costo de mantener lo que ya no funciona","Dejar ir para crear espacio nuevo","Ciclos naturales de muerte y renacimiento","Energía y mantenimiento en relaciones, proyectos y hábitos"]', 'A veces lo más sano es dejar morir ciertas cosas para que nazcan otras nuevas.', '7d7Sc1iNzC1Hz1kJqVlWt7', 'published', datetime('now'), datetime('now'));
